Add base files for flask image with flake8 and autopep8
techservicesillinois/secdev-quarantinenetwork pull request #1
Opened 2020-05-11 21:16 UTC by zcarrington

+ Add Dockerfile
+ Add Makefile
+ Add requirements file
+ Add basic app file with canary endpoint
+ Update readme

2020-05-11 21:19 UTC, MKletz approved these changes

2020-05-12 19:18 UTC, ddriddle requested changes
@zcarrington After you have the `make test` feature added I also recommend you enable Drone, and add a `.drone.yml` file with the following contents:

```
pipeline:
  build:
    image: python:3.8
    commands:
      - make deps
      - make test
```

Note that `make deps` should install all requirements needed for testing and running the code. I recommend the following be added to the Makefile:

```
deps:
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
```

2020-05-12 19:18 UTC, ddriddle commented on requirements/requirements.in
> +flake8
I recommend moving the `flake8` and `autopep8` deps into a separate `requirements-dev.txt` file. I also recommend you move the `requirements` files to the top-level. I have never seen a `requirements` directory in use before. It is a non-standard practice.

2020-05-12 19:18 UTC, ddriddle commented on Makefile
> +.PHONY: build run clean shell
Add `all`.

2020-05-12 19:18 UTC, ddriddle commented on Makefile
> +
Add a `test` that runs `pep8` and future unit tests.

2020-05-12 19:21 UTC, ddriddle commented
@zdc to enable Drone for this repo email: techservices-git@illinois.edu.

2020-05-12 19:25 UTC, ddriddle commented
@zdc you can check if a Drone build succeeds by checking: 

https://drone.techservices.illinois.edu/techservicesillinois/secdev-quarantinenetwork

You can also add a markdown badge your README.md:

```markdown
[![Build Status](https://drone.techservices.illinois.edu/api/badges/techservicesillinois/secdev-quarantinenetwork/status.svg)](https://drone.techservices.illinois.edu/techservicesillinois/secdev-quarantinenetwork)
```

2020-05-12 19:26 UTC, ddriddle commented on README.md
> +
Please Add a badge here for Drone:

```
[![Build Status](https://drone.techservices.illinois.edu/api/badges/techservicesillinois/secdev-quarantinenetwork/status.svg)](https://drone.techservices.illinois.edu/techservicesillinois/secdev-quarantinenetwork)
```

Please note that this points to the `master` branch.

2020-05-12 20:43 UTC, edthedev approved these changes
Approved - pending the changes requested by David.

2020-05-21 17:45 UTC, ddriddle approved these changes

2020-05-21 18:01 UTC, tzturner approved these changes

2020-05-21 18:02 UTC, merged